name: Monitoramento de Preços

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Execute a cada 5 horas

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
    - name: Verificando o código
      uses: actions/checkout@v2

    - name: Configurando o Chrome e o ChromeDriver
      uses: browser-actions/setup-chrome@latest

    - name: Configurando o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Instalando as dependências
      run: |
        pip install selenium requests

    - name: Conceder permissões de execução ao chromedriver
      run: |
        chmod +x drivers/chromedriver.exe

    - name: Executar script de monitoramento
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cd automacao
        python script.py

